[package]

name = "rusty-csv-diff"
version = "0.0.1"
authors = ["Irek Fakhrutdinov <irekfakh@gmail.com>"]

[dependencies]
docopt = "*"
rustc-serialize = "*"

[dependencies.log]
git = "https://github.com/rust-lang/log.git"
